### ISSUE TITLE
mongoose v6

### ISSUE THREAD

**Issue by spencersteers** [joegoldbeck/mongoose-encryption#102]
Was hoping to upgrade to mongoose v6 but ran into some issues with subdocument decryption. I narrowed it down to this addition in mongoose: https://github.com/Automattic/mongoose/blob/da1f4bdc8e7fceb248c07287ea76131c9e011616/lib/document.js#L815. 

It looks like mongoose-encryption is setting both `doc` and `obj` to the same object reference causing the fields to get deleted in the above. 

If I comment out this line: https://github.com/joegoldbeck/mongoose-encryption/blob/02b1ba176c377f91ce81b6eb63038589007e37e2/lib/plugins/mongoose-encryption.js#L258 then things start working correctly again.

Was hoping to get some insight on why `this._doc` is getting set like this. Apologies if I am missing something obvious - still wrapping my head around how mongoose and this library interact with one another.

**Comment by joegoldbeck** [comment]
Great catch @spencersteers! Fixed in 2.1.2

As to what that was there in the first place, my best recollection is that it was required in an earlier version of Mongoose :)

I've confirmed that it works for Mongoose 5 & 6 though, and improved CI so that tests are run against both 5 and 6.

**Comment by spencersteers** [comment]
@joegoldbeck Great - thanks for the quick turn around!
