### ISSUE TITLE
Support mongoose v4

### ISSUE THREAD

**Issue by wlingke** [joegoldbeck/mongoose-encryption#12]
Any plans to support mongoose v4? It does not work with current mongoose encryption

**Comment by joegoldbeck** [comment]
Ideally yes. Looking through the [migration guide](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) and [history] (https://github.com/Automattic/mongoose/blob/master/History.md)  I'm not seeing anything in particular that looks breaking, but yep, failing tests left and right. I'll try to take a look in the next couple weeks - hopefully it's something basic that will also be backwards-compatible.

**Comment by wlingke** [comment]
Sounds good - looking forward to it!

**Comment by wlingke** [comment]
Hey there, any updates on this?

**Comment by joegoldbeck** [comment]
Hey @wlingke, realistically, I don't see having time to look into it within the next month. Would be happy to take a look at any PRs though.

**Comment by wlingke** [comment]
@joegoldbeck Okay - I will try to find some time to check it out. If you have any thoughts as to where some of the problems might be, let me know.

**Comment by wlingke** [comment]
@joegoldbeck 

So I was able to fix one bug and spent a bunch of time investigating another..

One issue that  I cant figure out is "Array Embedded, when only child is encrypted, document.save(), should persist child as encrypted". This issue is tied to many others so if we can get this, we will have made good progress. 

So the children documents that are returned from the parent's `find()` are incorrect - you get children that look like:
```
{
  emitter: [Object]
  emitted: {},
  ended: true
}
```
Instead of the actual db entry.

This happens because in `pre('init')`, we are passed this object in the callback's `data` attribute. So something is happening with mongoose that is causing this random object to be returned instead of our original object.

I traced this back to mongoose document.js line 315 and from there documentarray.js line 188 - this is where the DB value gets converted into this weird object. However, I can't see to figure out why this is the case.

This is quite odd because normal objects saved in embedded arrays work correctly and the mongoose-encryption is saving isn't much different.

Do you think you could look at this and see if you can help with it? My knowledge of mongoose internals isn't as good but it seems you know much more about it.

**Comment by burtonjc** [comment]
@wlingke, @joegoldbeck I think the problem you ran into with the subdocuments being promises is actually a bug in mongoose 4. I opened up Automattic/mongoose#3207 to fix it. If I can get that PR merged in mongoose, I would be happy to look at finishing this issue off.

**Comment by joegoldbeck** [comment]
@wlingke thanks so much for looking into this further and highlighting the issue

@burtonjc yeah it does indeed look like a mongoose bug - thanks for pursuing that on the mongoose end!

**Comment by wlingke** [comment]
@burtonjc @joegoldbeck I added my PR #17 which includes a small fix for Buffer types not being deciphered correctly

**Comment by burtonjc** [comment]
@joegoldbeck @wlingke My PR just got merged into mongoose, and [my fork of mongoose-encryption](/burtonjc/mongoose-encryption) is down to 3 test failures. All three failures stem from one behavior change in mongoose 4 around how pre-save hooks get called. Previously, pre-save was called on subdocs first and then on the parent doc. This allowed mongoose-encryption to encrypt the children first, then encrypt the parent including the children as authenticated fields. In version 4, pre-save is called on the parent first, and then on it's subdocs. The result is the `_ac` on the parent doc is built using unencrypted children at save time, but then on init, the expected `_ac` is built using the encrypted children. Thus we are getting authentication failures for encrypted sub docs.

I'm not quite sure how to handle this yet. Any thoughts?

**Comment by burtonjc** [comment]
I also opened https://github.com/Automattic/mongoose/issues/3219 to see if we can figure anything out for this on the mongoose end.

**Comment by joegoldbeck** [comment]
@burtonjc Thanks for tracking this down! That sounds like an unintended change Mongoose-side, so hopefully they'll be open to a fix. It's not clear to me whether it would be possible to untangle given the current 4.x order. The LIFO order of the middleware (in terms of save vs init) that 3.x has is pretty key.

**Comment by burtonjc** [comment]
I just opened https://github.com/Automattic/mongoose/pull/3220 to get back to the original ordering of pre-save middleware in mongoose.

**Comment by burtonjc** [comment]
@joegoldbeck there is a test for
```
Array EmbeddedDocument
    Encrypted embedded document when parent has validation error and doesnt have encryptedChildren plugin
      should return encrypted embedded documents after failed parent save 
```

With https://github.com/Automattic/mongoose/pull/3220, this test fails because validation on the parent doc happens before encryption on the children. My hunch is this test was written because it is how the code worked, not necessarily because it is how we *want* it to work. It seems to me if a save fails, you still want everything unencrypted so you can keep working with the document. Do you agree? If so, I will change the test to make sure the children are unencrypted. If not, I will revise my PR.

**Comment by joegoldbeck** [comment]
I believe you're right that the test was characterizing the behavior. that said, if we update the test, then it'll fail under mongoose 3.x, which is non-ideal. the test below the one you mention: `Encrypted embedded document when parent has validation error and has encryptedChildren plugin, is really more how we want it to work, as the encryptedChildren plugin makes sure the subdocuments get unencrypted.

so, Mongoose 4.x has the correct behavior natively, while 3.x needs the `encryptedChildren` plugin to achieve the desired behavior. What about changing the test as you suggest, but only having it run under 4.x?

**Comment by burtonjc** [comment]
Would you prefer to have me duplicate the test and have the test as it run under 3.x and then my updated test run under 4.x?

**Comment by joegoldbeck** [comment]
sure sounds good!
