### ISSUE TITLE
Model.populate does not work?

### ISSUE THREAD

**Issue by mshi** [joegoldbeck/mongoose-encryption#13]
I have a few fields encrypted in a Model. When I use the static Model.populate method, the fields do not get decrypted (undefined)

Is this usage not supported? Do I have to use Model.find instead?

Thanks

**Comment by joegoldbeck** [comment]
Could you be a bit more specific about what you're doing? I'm not sure exactly how `.populate` works, but  it should work as long as it runs the `pre 'init'` middleware (I don't see why it wouldn't). Would it work for your use case if you did `Model.find` and then `doc.populate`? It might be that with the order that Mongoose runs `Model.populate` and the `pre init` middleware that's the only way that it works.

**Comment by mshi** [comment]
Model.populate allows me to populate based on an existing object (even partial) in place.  Basically I'm doing this:

I have a model called `User`, and within it is an array `supervising`. The array contains several fields, one of which is `child`, which is an `ObjectId` to the model `Child`.  The user model/object is stored (like a session store) and retrieved in various locations when needed. The example below, allows me to populate the 'Child' model within each of the elements in the `supervising` array. This allows me to populate what I need without first getting all the ids I need from the array, and then calling find (although I'm using that as a workaround for now).

```javascript
User.populate(req.user.supervising, {path: 'child', select: 'name surname', model: 'Child'}, function (err, populated) { ... });
```

**Comment by joegoldbeck** [comment]
Are the fields storing ObjectId's themselves encrypted? I wouldn't be surprised if Mongoose was trying to look up and populate those references before running the `pre 'init'` middleware, in which case the population would fail.

**Comment by mshi** [comment]
No, the fields with ObjectIds are not encrypted. I think it might be Mongoose looking it up using find with projection.

This leads to my side note that if you do Model.find and then pass projection parameters, the entire thing fails. I am forced to get the entire model.

**Comment by joegoldbeck** [comment]
Hmmmm, not sure what's going on here then, other than maybe something about the order in which Mongoose runs the middleware, or whether it runs them at all for `.populate`. Given that there's a workaround, I don't quite have time to dig into it unless it's a more common issue than I realize. I will definitely accept pull requests if you find a fix though!

I appreciate the report!
