### ISSUE TITLE
v1.1.0 in npm broke Model.save

### ISSUE THREAD

**Issue by molekilla** [joegoldbeck/mongoose-encryption#15]
FYI, had to rollback to 1.0.1

**Comment by joegoldbeck** [comment]
To clarify, `document.save` (i.e. Model#save) still works, right?

```
var fluffy = new Kitten({ name: 'fluffy' });
fluffy.save(function (err, fluffy) { ... 
```

Is `Model.save` a class method? I can't actually find it in the api docs. Can you give me a bit more info on what you're doing, your mongoose version, and the error?

Thanks for the report!

**Comment by molekilla** [comment]
Settings not working
-    "mongoose": "4.0.1",
-    "mongoose-encryption": "^1.0.1",

Settings working for me
+    "mongoose": "4.0.4",
+    "mongoose-encryption": "1.0.1",

**Comment by joegoldbeck** [comment]
Sounds likes this should be fixed by #19. Has been merged and should be released along with #20 as 1.2.0 in the next couple days.

**Comment by joegoldbeck** [comment]
1.2.0 is up on npm, and Mongoose has been updated with a few fixes from @burtonjc. Between those, does 1.2.0 work for you?

**Comment by molekilla** [comment]
Will try this week, thanks a lot for the update!
