### ISSUE TITLE
Question: Able to use findOneAndUpdate?

### ISSUE THREAD

**Issue by noahbornstein** [joegoldbeck/mongoose-encryption#21]
Are you able to use `findOneAndUpdate([query], [doc], [options], [callback])` on encrypted/authenticated fields? (`findOneAndUpdate` issues a MongoDB `findAndModify` update command.) I am assuming it isn't supported since `update` is not possible.

**Comment by joegoldbeck** [comment]
Not supported since Mongoose middleware won't fire at that point.

Additionally, given the method we're using, all encrypted/authenticated fields need to be saved at once, which seems like it would make a findOneAndUpdate a fair bit less useful, or at least rather constrained in its use.
