### ISSUE TITLE
Authentication fails with a populated ref on pre init

### ISSUE THREAD

**Issue by aliatsis** [joegoldbeck/mongoose-encryption#23]
If a schema has a field that is a 'ref' to another model and this 'ref' gets populated on a query, authentication will fail.

I dug into the code and here is the broken flow.

1. Document without populated ref gets saved to the DB
2. Query for the document and populate the ref
3. The pre-init hooks gets called with 'data' as a vanilla object, but the 'ref' field within it is already a mongoose model due to population
3. When authenticating, this 'data' object from the pre-init hook is used to computeAC()
4. Since the ref field is already a populated model, the 'expectedHMAC' cannot equal the ac buffer

**Comment by joegoldbeck** [comment]
I assume this problem only occurs when the ref is one of the authenticated fields. Not sure there's anything to do about this, other than perhaps filing a mongoose issue asking for a hook that exposes the original document even when populating.

**Comment by joegoldbeck** [comment]
Marking `wontfix`, but if other users stumble onto this issue, I'm certainly happy to look at any PRs that fix it.
