### ISSUE TITLE
Error: Authentication code missing

### ISSUE THREAD

**Issue by globlee** [joegoldbeck/mongoose-encryption#25]
I get the error: "Error: Authentication code missing" after doing a schema.findone

Apparently this is an error with signing

My code is extremely basic, just two lines and I have checked it about 25 times to make sure it matches the example
I have tried with the secret string, with the codes, with encrypted fields and without (full document).
example:

var secret = "1WqEMNO7vdp4CY3YPzE4dL3tnng1ZfjeziBXibPecOgL7SnEdUWaqoyGCyoozAAZOwajkIJt0UL5cdQiHV18EEzhSNn2OtW8JTlpjOYxwB3C21PV4ODXgF1YQ0oH9A";

UserSchema.plugin(encrypt, { secret: secret});

Are there any common reasons for this error, or can you tell me more about what _ac is so I can try to figure out whats wrong here?

**Comment by globlee** [comment]
duh. needed requireAuthenticationCode: false

**Comment by joegoldbeck** [comment]
Yup! Alternatively you can migrate your existing collection with `#migrateToA`. https://github.com/joegoldbeck/mongoose-encryption/tree/7a71d633958688f86823bc790d3817bea2c0a774#getting-started-with-an-existing-collection which will sign and encrypt all the documents

Be sure to backup your database first!
