### ISSUE TITLE
Why I'm not able to save email as a encrypted field

### ISSUE THREAD

**Issue by piyushsynechron** [joegoldbeck/mongoose-encryption#27]
When I'm trying to save email field using mongoose encryption it saves data as a plain text not in _ct.
After read your document I tried with 
userSchema.plugin(encrypt, {
                                secret: secret , 
                                excludeFromEncryption: ['email'],
                                additionalAuthenticatedFields: ['email']
                           });
but again it's saving email as plain text field in DB.
I'm trying with below data 
admin = new User ({"email" : 'admin@test.com', "password" : "123" , "role" : "Admin" });
All fields encrypted except email why?
When I changed field name it will be encrypted but I don't want to change field name from email to something else.
So can you please help me out how to save above email as encrypted field.

**Comment by joegoldbeck** [comment]
Any field in `excludeFromEncryption` will *not* be encrypted. 

If you use the default settings, `email` should be encrypted along with all the other fields (except for `_id`).
```
userSchema.plugin(encrypt, {
secret: secret
});
```

**Comment by joegoldbeck** [comment]
If `email` isn't encrypted with the default options, another possibility is that you have an index set up on that field, which would mean that it won't be encrypted by default. Since nothing actually gets saved under the encrypted keys (instead it's packed inside `_ct`) indexes won't do anything on those fields. By default we assume that if a field has an index, then that field is intended as a common target of queries, and therefore shouldn't be encrypted (which would prevent querying on that property).

If an index is indeed set up, and you don't want to make other code changes, you can be explicit about which fields you do want to encrypt with the `encryptedFields` option.

**Comment by piyushsynechron** [comment]
@joegoldbeck , 
1) yes , I already tried with below code but except email all field getting encrypted
userSchema.plugin(encrypt, {
secret: secret
});
2) Yes , you are right Email has an indexed with unique when I removed index it will encrypt email.
3) If I want to save email with index so can you please help me how to do ?
4) I knew this option "encryptedFields" , It's working with email but in this option I need to mention all field name which I don't want because I've many field in user collection and want to encrypt all fields.

Ques: If I want to save email with index so can you please help me out how to do ??

Thanks for your quick response

**Comment by joegoldbeck** [comment]
Unfortunately, using this plugin there is no way to both encrypt a field *and* force a unique index on it. (Or any index).

The email field is encrypted in such a way that the same email encrypted two separate times will end up as two different, and apparently random, values (this is to avoid vulnerability to a collision attack). So the only way to ensure that an email you are saving is unique would be to retrieve *all* your user documents, and check the decrypted email field of each, to ensure that the one you are saving is unique.

**Comment by piyushsynechron** [comment]
Thanks @joegoldbeck , got you.
after stored encrypted data in database now I'm facing problem on application level with passport.js.
When I use findOne with criteria it doesn't work , where findById , findOne without criteria, find without criteria works.
can you please give us suggestion ?
Trying with below code
       User.findOne({ 'email' :  email }, function(err, user) {
            //Here I'm getting user and err both NULL
            if (err)
                return done(err);

            if (user) {    
                return done(null, false, req.flash('message', 'Email already exists.'));
            } else {
                // if there is no user with that email
                // create the user
                var newUser            = new User();

                // set the user's local credentials
                newUser.email      = email;
                newUser.password   = newUser.generateHash(password);

                // save the user
                newUser.save(function(err) {
                    if (err)
                        throw err;
                    return done(null, newUser);
                });
            }

        });

**Comment by joegoldbeck** [comment]
If a field is encrypted you can't query based on that field. In other words, for `User.findOne({ 'email' :  email }` to return any results, `email` must *not* be one of the encrypted fields.

**Comment by piyushsynechron** [comment]
Ok thank you @joegoldbeck
