### ISSUE TITLE
Proper Version?

### ISSUE THREAD

**Issue by bobby-brennan** [joegoldbeck/mongoose-encryption#33]
I noticed 0.11 is the latest version on npm, whereas 1.3.0 is the current version on master.

Is 1.3.0 ready for usage? It'd be helpful to add a note in the README that explains the discrepancy, and which version is recommended for different environments (e.g. 0.11 for production and 1.3.0 for bleeding edge dev)

**Comment by joegoldbeck** [comment]
oh good catch! 0.11.1 was a retroactive release to address https://github.com/joegoldbeck/mongoose-encryption/issues/31. Didn't realize it would get set to the latest release when it got pushed. 1.3.0 is indeed ready for usage. Updated the npm tags to clarify this.

Thanks for letting me know about this!
