### ISSUE TITLE
underscore v1.5 peer is not available

### ISSUE THREAD

**Issue by roymap** [joegoldbeck/mongoose-encryption#35]
You get a warning when you install mongoose-encryption:

`npm WARN mongoose-encryption@1.3.0 requires a peer of underscore@1.5.x but none was installed.`

underscore is at v1.8.3 right now.

Can you update to the latest version of underscore (or move to the latest lodash)?

**Comment by joegoldbeck** [comment]
Fixed in v1.3.1 51a590664c2e1a36c99c5840f7eaa48b7ba16b94
