### ISSUE TITLE
Select support for encrypted fields

### ISSUE THREAD

**Issue by awilson28** [joegoldbeck/mongoose-encryption#37]
Many thanks for this plugin! I've only used it for a few hours and it seems to work pretty well. However, I've noticed that if I add a field to the encrypted fields array like so: 

`UserSchema.plugin(encrypt, { encryptionKey: encKey, signingKey: sigKey , encryptedFields: ['firstName', 'lastName', 'pin']});`

I cannot de-select this field

`return mongoose.model('User').findById(u._id).select('-pin')`

This query returns the user document with the pin field. However, if I remove the pin field from the `encryptedFields` array, selecting and deselecting works as expected. 

I've noticed that even if I add  `select: false` to the schema definition for this field, the de-select still doesn't work. Would be great to be able to de-select fields that are encrypted.

**Comment by joegoldbeck** [comment]
Yep, this is a known limitation of the plugin (noted in the readme). All the encrypted fields are bundled together before encryption and saved in the field `_ct`. So, any select that includes `_ct` will get all the encrypted fields. There may be a way to intercept the select, modify the query based on whether or not selected fields are encrypted or not, and then delete unselected fields before returning the document. I suspect full support for select is complicated, but if it's possible without too much complication, happy to look at a PR.

**Comment by awilson28** [comment]
@joegoldbeck thanks for this clear and timely response, Joe! I'll research this enhancement further.

**Comment by GautierT** [comment]
Hi !
Any update on this ?

**Comment by joegoldbeck** [comment]
As noted above, I don't think this is possible with the mongoose plugin api. Closing.
