### ISSUE TITLE
find() method doesn't retrieve data when field filter is applied.

### ISSUE THREAD

**Issue by ashkrishan** [joegoldbeck/mongoose-encryption#38]
First of all many thanks for this package. Trying to work it out in my app but having few issues. Hope you could help

```
Message.find({'content': 'this is test'}, function(err, messages) {
    if(err) {
        console.log(err);
    }
    console.log(messages)
});
```

Doesn't retrieve any data from the collection when above filter is applied in find method.

However, when find({}) on its own is applied:
```
Message.find({}, function(err, messages) {
    if(err) {
        console.log(err);
    }
    console.log(messages)
})

```

returns correctly:
```
[ { content: 'this is test',
    __v: 0,
    _id: 577bc0ad1bd99a082eed2606 } ]
```

Using version "mongoose-encryption": "^1.3.1", (from package.json)

**Comment by joegoldbeck** [comment]
Yup, this is expected behavior. You can't query over encrypted fields. This is because they are stored encrypted in the database and use a random initialization vector, such that there is no one-to-one match between a value and its encrypted version to prevent against collision attacks.

**Comment by ashkrishan** [comment]
Thanks for coming back to me so quickly. 

In that case what would you suggest the best way to filter with mongoose-encryption on whole document,  Should I pull all data from collection with find() in an array and use that? Or should I serialize in a json on application/node server, then query json with applied filter and delete after sending response to client?

Thanks for you help.
Ash

**Comment by ashkrishan** [comment]
Never mind ignore it. I have sorted it out. cheers

**Comment by seanhelvey** [comment]
what did you end up doing @ashkrishan? I'm not sure what "can't query over encrypted fields" means, because the README says that finds work as expected right @joegoldbeck?

**Comment by joegoldbeck** [comment]
I'll update the README to make it clearer. If a field is encrypted, it cannot be queried.
