### ISSUE TITLE
findOne on child-fields not working

### ISSUE THREAD

**Issue by phillipwei** [joegoldbeck/mongoose-encryption#39]
For the following structure
```
item: {
    subItem: {
        x: 10103759419439161
    }
}
```
The query `Item.findOne({"subitem.x": "123"})` returns an object when not encrypted, but fails to when encrypted. Is there a work around, or am I using this package incorrectly?

**Comment by joegoldbeck** [comment]
This is expected behavior. You can't query fields that are encrypted. I'll update the docs to make this clearer
