### ISSUE TITLE
Support discriminators

### ISSUE THREAD

**Issue by mattdawson** [joegoldbeck/mongoose-encryption#41]
If I have a schema 'Parent' with a child schema 'Child' where parent has an encrypted field,
when saving child, the encrypted parent field is not encrypted.
I can fix this by placing the encrypt for the parent field on all the child types.
But, if I also place an encrypt on the child type at the same time as the parent type the pre-save method clears the field as it as called twice, once for each type in the hierachy.  The first call encrypts and removes the fields the second call finds the fields empty and erases them.

**Comment by mattdawson** [comment]
It occurs to me the way it works would prevent having enrypted fields in multiple places in the hierachy one would always overwrite the others _ct and _ac

**Comment by joegoldbeck** [comment]
Thanks @mattdawson for filing the issue. I'm not sure I fully understand. Can you post a code snippet that demonstrates the behavior? Which version of Mongoose are you using? Thanks!

**Comment by mattdawson** [comment]
Further testing has found this is caused by {minimize: false}, this is related to #42

**Comment by mattdawson** [comment]
`var mongoose = require('mongoose'), encrypt = require('mongoose-encryption');

// base object
var nodeSchema = new mongoose.Schema({
	name: {
		type: String,
	},
	nodeSecret: {
		type: String
	}
}, {
		//minimize: false,
		discriminatorKey: 'kind'
	});

nodeSchema.plugin(encrypt, {
	encryptionKey: "xpAtVJ3Bh3Dg/JeQBC2Kbc8E6LcZrcsEKIWGzWSpDuM=",
	signingKey: "cYazwVbo4YUIEAMSp7YAFSZjCpy02WBTFJKXCGMYpggqdaYU9sSrRpvIVmlIRan4iAG/12ogodHJ7G1U0nW5Yw==",
	encryptedFields: ['nodeSecret']
});

var Node = mongoose.model('Node', nodeSchema);

// child object
var deviceSchema = new mongoose.Schema({
	childField: {
		type: String,
	},
	childSecret: {
		type: String,
	}
}, {
		//minimize: false,
		discriminatorKey: 'kind'
	});

deviceSchema.plugin(encrypt, {
	encryptionKey: "xpAtVJ3Bh3Dg/JeQBC2Kbc8E6LcZrcsEKIWGzWSpDuM=",
	signingKey: "cYazwVbo4YUIEAMSp7YAFSZjCpy02WBTFJKXCGMYpggqdaYU9sSrRpvIVmlIRan4iAG/12ogodHJ7G1U0nW5Yw==",
	encryptedFields: ['childSecret']
});

// This is a child of Node, the descriminator key determines the sub-type
var Device = Node.discriminator('Device', deviceSchema);

mongoose.connect('mongodb://127.0.0.1/test');
var db = mongoose.connection;

db.once('open', function() {
	new Device({name:"name", nodeSecret: "nodeSecret", childField: "child", childSecret: "childSecret"}).save(function(err, node) {
		console.log(err,node);

		// Now check the database, it still has the plain text fields in it, and the encryption is empty
		Device.find({}, function(err, result) {
			console.log("result",result);
		});
	}); 
});`

**Comment by mattdawson** [comment]
Looking at the schema for Device in the test code, it appears the there's no route to the parent model, so no way to find out the parent encrypted fields.  But all parent fields are included in the child model, so if we re-specify encryption of the parent encrypted fields in the child, and prevent the double pre-save event issue then it'd basically be working.

**Comment by joegoldbeck** [comment]
Oh I see what's going on here. The parent and child terminology was a bit confusing since I've usually heard that refer to [subdocuments](http://mongoosejs.com/docs/subdocs.html)

It's not clear to me how to add straightforward support for the code above, and it does make sense that adding the plugin (and therefore the middleware) twice to a schema with different options would cause issues. Mongoose doesn't provide a method for plugins to interact with each other.

I think the way to do this in your case would be to add the plugin only to the base schema (`nodeSchema` above) and include all the encryption options at that time.

So:

```
nodeSchema.plugin(encrypt, {
    encryptionKey: "xpAtVJ3Bh3Dg/JeQBC2Kbc8E6LcZrcsEKIWGzWSpDuM=",
    signingKey: "cYazwVbo4YUIEAMSp7YAFSZjCpy02WBTFJKXCGMYpggqdaYU9sSrRpvIVmlIRan4iAG/12ogodHJ7G1U0nW5Yw==",
    encryptedFields: ['nodeSecret', 'childSecret']
});
```

**Comment by joegoldbeck** [comment]
@mattdawson did the above work for you?

**Comment by mattdawson** [comment]
Hi, I ended up putting/repeating the encryption on each of the child/sub schemas.  I think the save events weren't firing when I put them on the parent.  I'd suggest closing this and if someone else has the same issue they can reopen this bug.

**Comment by joegoldbeck** [comment]
Sounds good!
