### ISSUE TITLE
Using {minimize: false} option on mongoose schema causes migration to clear fields

### ISSUE THREAD

**Issue by mattdawson** [joegoldbeck/mongoose-encryption#42]
mongoose: 4.5.3
mongoose-encryption: 1.3.1

When migrating docs the "migrate no previously encrypted docs" at line 527 of index.js encrypts the document (this clears the plain text fields) then calls save, which triggers the pre-save which also encrypts documents, but since the plain text fields were already cleared by migrate it erases thier data.
This only occurs when the schema has {minimize: false} as an option.

This might be fixed by not encrypting inside the migratation and relying on the pre save handler instead.

**Comment by joegoldbeck** [comment]
Hmmm, that is strange. The pre-save should not be triggered at all because middleware should be turned off by https://github.com/joegoldbeck/mongoose-encryption/blob/0a7f480b4a040d4446fc19b08b51bae6e34fe3e7/index.js#L507

**Comment by joegoldbeck** [comment]
Oh actually, I think I see what's happening. When running the actually migration, you should only attach the migrations plugin to the schema, not the main plugin as well. Does that explain the issue?

// userSchema.plugin(encrypt, { .... }); // this should be commented out
userSchema.plugin(encrypt.migrations, { .... }); // this should be added
User = mongoose.model('User', userSchema);
User.migrateToA(function(err){
    if (err){ throw err; }
    console.log('Migration successful');
});

**Comment by mattdawson** [comment]
Bah, I removed the main encryption plugin, and it poked anything I edited from then on.
I get errors like Unexpected token X at Object.parse (native) at Object.schema.methods.authenticateSync.
An example acBuf now looks like WWREMTFkWHdRY243NkxkK01nMmh1Z3hyNXd6ODJ6NTV4MVJrZUVtSHRoU25XeUpmYVdRaUxDSmZZM1FpWFE9PQ==
Which when you take the 33 chars off the front for the front for version and basicAc, the slc becomes Xd6ODJ6NTV4MVJrZUVtSHRoU25XeUpmYVdRaUxDSmZZM1FpWFE9PQ== which is wrong, it should have been a json encoded list of fields.   Strange...

**Comment by joegoldbeck** [comment]
Hmmm, so to be clear, you should run a script that looks like
```
userSchema.plugin(encrypt.migrations, { .... }); // this should be added
User = mongoose.model('User', userSchema);
User.migrateToA(function(err){
if (err){ throw err; }
console.log('Migration successful');
});
```

and then go back to just `UserSchema.plugin(encrypt, { .... });` in the application code

**Comment by mattdawson** [comment]
Ok, so in my test code I replace encrypt with encrypt.migrations, and it no longer encrypts fields when objects are created.  Does encrypt migrations only work for the migrateToA function?  If so would it not be better to require defining both encrypt and encrypt.migrations and then to rely on the pre save handler?  Then I wouldn't need to modify my code twice on moving to a new environment?

**Comment by joegoldbeck** [comment]
That is correct behavior. My earlier answer might have been a bit confusing. 

Migrations should be run only once, so you should execute a script for them which includes `encrypt.migrations`, but not plain `encrypt`. The code that is running your server can keep the `encrypt` plugin so that new documents are encrypted.

**Comment by mattdawson** [comment]
Can you do a check for importing both encrypt and migration at the same time and error if they both exist?

**Comment by joegoldbeck** [comment]
Added this check in `1.4.0`
