### ISSUE TITLE
How can I encrypt and find fields upon populating it

### ISSUE THREAD

**Issue by muhammadfaizan** [joegoldbeck/mongoose-encryption#43]
I had a data, i encrypted it, and now its not getting populated with all the fields that were there.

**Comment by joegoldbeck** [comment]
Hi @muhammadfaizan thanks for filing the issue. If a field is encrypted, you can't find based on it. Only unencrypted fields can be used in a query. Does that answer your question, or are you retrieving documents successfully and finding that certain fields are now missing?

**Comment by muhammadfaizan** [comment]
lets me give you example
```
mongoose.Schema({
myReferencedObject : { type: mongoose.Schema.ObjectId, ref: 'otherCollection'}

})

mongoose.pre('save', function(){  this.populate('myReferencedObject') } );
```

...

**Comment by joegoldbeck** [comment]
Ah I see. Does it work any differently if you reverse the order of those two statements? As long as your `pre-save` middleware runs before the mongoose-encryption middleware I'd think that would work just fine.

**Comment by muhammadfaizan** [comment]
let me try that, if it helps I'd be really glad honestly !
if it doesn't I'd create a PR.

**Comment by joegoldbeck** [comment]
did it work?

**Comment by muhammadfaizan** [comment]
i had to migrate too, so it worked this way

1) i ran code with migration plugin, once migrated.
`myschema.plugin(encrypt.migration, {
        encryptionKey: encKey,
        signingKey: sigKey ,
        encryptedFields: ['field1', 'field2']
    });` 
2) i tried API, i was getting same _ac fields...
3) then i removed _migration_ from encryption
` myschema.plugin(encrypt, {
        encryptionKey: encKey,
        signingKey: sigKey ,
        encryptedFields: ['field1', 'field2']
    }); `
4) removed migration code

`mycollection.migrateToA(function(err){
    if (err){ throw err; }
    console.log('Migration successful');
})`
It worked.. Thanks
Well shouldn't it work with migration too

**Comment by joegoldbeck** [comment]
Great!

Ideally, the migration should be run once as a separate script rather than living inside your application code, but glad this worked out for you. I'll clarify that in the docs
