### ISSUE TITLE
Key Rotation

### ISSUE THREAD

**Issue by mbonig** [joegoldbeck/mongoose-encryption#49]
I understand the plugin doesn't have any support for key rotation, but do you have, or could you write, a recommended strategy for handling this? 

I assume it'd look something like this:

Load all records from the database.
Save all records to a new collection that is not encrypted
Delete all encrypted records.
Rotate Key
Load all unencrypted records from the database
Save all unencrypted records to the encrypted collection.

Thanks

**Comment by joegoldbeck** [comment]
That should work. Another similar option would be:

0) Begin downtime
1) Load all records from the encrypted collection.
2) Save all records to a new collection that *is* encrypted using the same options except including `collectionId` to match the *original collection name* and using the new key
3) [Rename the new collection](https://docs.mongodb.com/v3.2/reference/method/db.collection.renameCollection/) to overwrite the old one
4) Rotate key
5) Confirm success and bring back online

Either method requires downtime unfortunately, and certainly back everything up beforehand and confirm all documents have been migrated successfully before going live

**Comment by mbonig** [comment]
Thanks, I think that's a better approach as it means we're never seeing user records written un-encrypted.
