### ISSUE TITLE
Support for `SingleNested` document as of mongoose 4.8.0

### ISSUE THREAD

**Issue by victorparmar** [joegoldbeck/mongoose-encryption#50]
As of mongoose 4.8.0, singly nested documents no longer have the `EmbeddedDocument` constructor name, rather `SingleNested`. This does not currently work with the plugin unfortuntately :(

**Comment by victorparmar** [comment]
https://github.com/joegoldbeck/mongoose-encryption/pull/51

**Comment by joegoldbeck** [comment]
Fixed as of https://github.com/joegoldbeck/mongoose-encryption/releases/tag/1.5.0
