### ISSUE TITLE
Arrays of embedded documents not encrypted in Mongoose 4.8.1-4.9.0

### ISSUE THREAD

**Issue by joegoldbeck** [joegoldbeck/mongoose-encryption#54]
Issue filed at https://github.com/Automattic/mongoose/issues/5085

**Comment by joegoldbeck** [comment]
Update. Fixed in mongoose:master https://github.com/Automattic/mongoose/commit/aae7c571933aa8622685e40149fd54d337b2b291

Will update this when merged into a Mongoose release

**Comment by joegoldbeck** [comment]
Fixed as of 4.9.2 https://github.com/Automattic/mongoose/blob/4.9.2/History.md

Next step is to either update peerDependencies to disallow these versions, or perhaps more simply, log a warning.

**Comment by nasospsa** [comment]
Also not working with previous 4.x versions of mongoose.
4.9.5 works just fine.

**Comment by joegoldbeck** [comment]
> Also not working with previous 4.x versions of mongoose.

Are you sure about that? I tested and it seemed specific to the version I listed up top

**Comment by nasospsa** [comment]
Tested it with 4.4.17

Not sure for other versions.

**Comment by garretblankenship** [comment]
I am having a similar issue with mongoose 4.13.9 & mongoose-encryption 1.5.0.

My schemas look like this:

`const ChatSchema = new Schema({
    sender: {
        type: Schema.Types.ObjectId, 
        ref: 'user'
    },
    message: {
        type: String, 
        default: ''
    },
    type: {
        type: String, 
        required: true,
        enum: ['audio', 'text', 'system']
    },
    created: {
        type: Date, 
        default: Date.now
    },
    meta: {
        ipAddress: {
            type: String
        },
        os: {
            type: {
                type: String
            },
            version: {
                type: String
            }
        },
        browser: {
            type: String
        },
        device: {
            type: String
        },
        machine: {
            type: String
        }
    },
    temporaryId: {
        type: String
    }
});

ChatSchema.plugin(encrypt, {
    encryptionKey: keys.mongoose.encKey,
    signingKey: keys.mongoose.sigKey,
    encryptedFields: ['message']
});

const ChannelSchema = new Schema({
    subscribers: [{
        type: Schema.Types.ObjectId, 
        ref: 'user'
    }],
    type: {
        type: String, 
        enum: ['direct', 'group'],
        required: true
    },
    active: {
        type : Boolean, 
        default: true
    },
    messages: [ChatSchema],
    unread: {
        type: mongoose.Schema.Types.Mixed,
        default: {}
    }
});`

When I push a new message into ChannelSchema.messages the message is not being encrypted. I don't know if this is a bug similar to above or if I am missing something from the documentation.

**Comment by garretblankenship** [comment]
Quick update for anyone else experiencing this problem I originally was calling Model.findOneAndUpdate with a $push which wasn't encrypting the sub-document field in the array. But when I found the parent document using `const parentDocument = Model.findOne` and then pushed the new subdocument in the array using `parentDocument.subDocumentArray.push()` and then called `parentDocument.save()` the field is encrypted in the subdocument.

**Comment by joegoldbeck** [comment]
Moving forward, we'll only be supporting Mongoose 5 and up, barring critical issues
