### ISSUE TITLE
How to Update a document ?

### ISSUE THREAD

**Issue by s0j0hn** [joegoldbeck/mongoose-encryption#55]
Hello,

How do i properly do a update on document which is fully encrypted ?
do i a have to delete it before ?

**Comment by s0j0hn** [comment]
There is a way, remove the document and the re-create it.
Otherwise there isno solution ?

**Comment by joegoldbeck** [comment]
Hi. If you use document-level functions like `save` to update the document, then it will work straightforwardly. You do not need to delete a document to update it.

http://mongoosejs.com/docs/api.html#model_Model-save

**Comment by haydarai** [comment]
@joegoldbeck any reason why it won't work with `update`?

**Comment by joegoldbeck** [comment]
Yep. From [the docs](http://mongoosejs.com/docs/middleware.html#notes)

> Pre and post save() hooks are not executed on update(), findOneAndUpdate(), etc.

http://mongoosejs.com/docs/middleware.html#notes

The plugin uses those hooks to encrypt/decrypt/sign the document. Relatedly, the commands listed above execute against the database, but encryption in this plugin is done at the document-level.
