### ISSUE TITLE
Support for custom encryption key per document

### ISSUE THREAD

**Issue by nasospsa** [joegoldbeck/mongoose-encryption#56]
I would like to have the option to encrypt the data of a document with a secret password, per user let's say.

Meaning that we would need the password each time to decrypt the documents of the user.

Is that an option you are going to pursue/develop?

**Comment by joegoldbeck** [comment]
Hi @nasospsa! Thanks for the feature request. I think this is out of scope for this project, the goal of which is to help protect user data from outside attackers not to hide it from the parent service itself. It's an admirable goal though. Certainly feel free to fork :)
