### ISSUE TITLE
Not encrypted when Model.insertMany()

### ISSUE THREAD

**Issue by ZacharyRSmith** [joegoldbeck/mongoose-encryption#61]
When I use Model.insertMany(), data is not encrypted.  But data is encrypted otherwise.

**Comment by joegoldbeck** [comment]
I believe this is standard Mongoose behavior, the hooks for saving and finding are document level. When you perform collection-level (`Model#whatever`) operations, you are closer to the raw Mongo driver.

You can create a bunch of Mongoose documents, call `doc#encrypt` on each of those, and then pass them into Model#insertMany to achieve what you are looking for.
