### ISSUE TITLE
Error when using validate of phone number in Schema. When retrieving user details error is thrown even when phone number is not entered  

### ISSUE THREAD

**Issue by tsudharsanprdxn** [joegoldbeck/mongoose-encryption#65]
I have defined a Schema which goes like this: 
let userSchema = new Schema({

..........................

'userMobileNo': {
		'type': String,
		'validate': [/^(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)\d{1,4}\)?[\s-]?(?:\(?0\)?[\s-]?)?)|(?:\(?0))(?:(?:\d{5}\)?[\s-]?\d{4,5})|(?:\d{4}\)?[\s-]?(?:\d{5}|\d{3}[\s-]?\d{3}))|(?:\d{3}\)?[\s-]?\d{3}[\s-]?\d{3,6})|(?:\d{2}\)?[\s-]?\d{4}[\s-]?\d{4}))(?:[\s-]?(?:x|ext\.?|)\d{3,4})?$/, 'Please enter a valid phone Number'],
		'trim': true
	},

............................

userSchema.plugin(encrypt, {
	'encryptionKey': encKey,
	'signingKey': sigKey,
	'encryptedFields': [userMobileNo]
});

The signup process goes well but when retrieving data of the user error is thrown. Even if user has not entered any number but if the validate is removed it works fine!

**Comment by joegoldbeck** [comment]
Thanks for the bug report. Happy to take a quick look. Could you let me know

Node version:
mongoose version:
mongoose-encryption version:

And also include the staketrace you see when this error happens?

**Comment by tsudharsanprdxn** [comment]
Node Version:  v6.11.4
Mongoose Version: 4.12.4
Mongoose-encryption Version: 1.5.0
ValidationError: userMobileNo: Please enter a valid phone Number
0|Kiddoo   |     at MongooseError.ValidationError (/var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/error/validation.js:28:11)
0|Kiddoo   |     at model.Document.invalidate (/var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/document.js:1636:32)
0|Kiddoo   |     at /var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/document.js:1508:17
0|Kiddoo   |     at validate (/var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/schematype.js:779:7)
0|Kiddoo   |     at /var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/schematype.js:797:7
0|Kiddoo   |     at Array.forEach (native)
0|Kiddoo   |     at SchemaString.SchemaType.doValidate (/var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/schematype.js:784:19)
0|Kiddoo   |     at /var/www/html/Sudharsan/kidoo/kiddoo-api/node_modules/mongoose/lib/document.js:1506:9
0|Kiddoo   |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
0|Kiddoo   |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by joegoldbeck** [comment]
Hmmmm, I wonder what value it's reading for the phone number. Can you make your validation message include the value itself, using `{VALUE}` as in this example?
```
validate: {
          validator: function(v) {
            return /\d{3}-\d{3}-\d{4}/.test(v);
          },
          message: '{VALUE} is not a valid phone number!'
        },
```

http://mongoosejs.com/docs/validation.html#custom-validators

**Comment by tsudharsanprdxn** [comment]
{ VALUE } in my case is "undefined" but since it is not required why is it still throwing error?

**Comment by tsudharsanprdxn** [comment]
Can I please get further help?

**Comment by joegoldbeck** [comment]
Hi @tsudharsanprdxn sorry for dropping off for a bit. My best advice for now would be to do a workaround 
```
'validate': {
  validator: function (v) { 
    if (v === undefined) return true;
    return /^(?:(?:(?(?:0(?:0|11))?[\s-]?(?|+)\d{1,4})?[\s-]?(?:(?0)?[\s-]?)?)|(?:(?0))(?:(?:\d{5})?[\s-]?\d{4,5})|(?:\d{4})?[\s-]?(?:\d{5}|\d{3}[\s-]?\d{3}))|(?:\d{3})?[\s-]?\d{3}[\s-]?\d{3,6})|(?:\d{2})?[\s-]?\d{4}[\s-]?\d{4}))(?:[\s-]?(?:x|ext.?|)\d{3,4})?$/.test(v);
},
  message: 'Please enter a valid phone Number'
}
```

The fact that this hasn't come up before makes me think this may be a transient change in Mongoose behavior, so unless it comes up again I probably won't update the lib myself. That said, I'm open to PRs with appropriate tests if you are another reader feels like digging in.

**Comment by tsudharsanprdxn** [comment]
I downgraded mongoose to various versions and checked but same error was thrown

**Comment by tanmayawasekar** [comment]
@joegoldbeck : I faced a similar issue as reproted by @tsudharsanprdxn . Can you find it out?

**Comment by joegoldbeck** [comment]
Hi @tanmayawasekar. Does the workaround I posted above solve the issue?

**Comment by tsudharsanprdxn** [comment]
@joegoldbeck I have used validation in pre save hook so that worked for me.
