### ISSUE TITLE
this in mongoose hooks not returning current object

### ISSUE THREAD

**Issue by tsudharsanprdxn** [joegoldbeck/mongoose-encryption#67]
I am using  following versions:
mongoose: 4.11.13
mongoose-encryption: 1.5.0

userSchema.pre('save',(next) => {
  console.log(this);
}
or
userSchema.post('save',(next) => {
  console.log(this);
}

Returns the following instead of the current document.
 
{ default: 
    { [Function: model]
      hooks: Kareem { _pres: [Object], _posts: {} },
      base: 
       Mongoose {
         connections: [Object],
         plugins: [],
         models: [Object],
         modelSchemas: [Object],
         options: [Object] },
      modelName: 'users',
      model: [Function: model],
      db: 
       NativeConnection {
         base: [Object],
         collections: [Object],
         models: [Object],
         config: [Object],
         replica: false,
         hosts: null,
         host: 'localhost',
         port: 27017,
         user: undefined,
         pass: undefined,
         name: 'kiddoo',
         options: [Object],
         otherDbs: [],
         _readyState: 1,
         _closeCalled: false,
         _hasOpened: true,
         _listening: false,
         db: [Object],
         _events: [Object],
         _eventsCount: 3 },
      discriminators: undefined,
      aggregatePaginate: [Function: aggregatePaginate],
      paginate: [Function: paginate],
      schema: 
       Schema {
         obj: [Object],
         paths: [Object],
         subpaths: {},
         virtuals: [Object],
         singleNestedPaths: [Object],
         nested: [Object],
         inherits: {},
         callQueue: [Object],
         _indexes: [],
         methods: [Object],
         statics: [Object],
         tree: [Object],
         _requiredpaths: [Object],
         discriminatorMapping: undefined,
         _indexedpaths: [Object],
         query: {},
         childSchemas: [Object],
         s: [Object],
         options: [Object],
         '$globalPluginsApplied': true },
      collection: 
       NativeCollection {
         collection: [Object],
         opts: [Object],
         name: 'users',
         collectionName: 'users',
         conn: [Object],
         queue: [],
         buffer: false,
         emitter: [Object] },
      Query: { [Function] base: [Object] },
      '$__insertMany': [Function],
      insertMany: [Function] } }

**Comment by tsudharsanprdxn** [comment]
@joegoldbeck Can you please look into this?

**Comment by joegoldbeck** [comment]
That looks to me like a bug in your application code, not in the plugin, actually. The [arrow syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) you're using explicitly passes through the value of `this` from the outer scope, rather than having it get set by the caller

I suspect if you use typical function syntax `function(next) {..}` the issue will go away.
