### ISSUE TITLE
encrypted fields in nested doc are undefined in post save response

### ISSUE THREAD

**Issue by som-soni** [joegoldbeck/mongoose-encryption#73]
Hi,

I have following schema. 

`
var mongoose = require('mongoose');
var encrypt = require('mongoose-encryption');
var secrets = require('../config/secrets');
var voltdbPlugin = require('./plugins/voltdb');

var nestedSchema = new mongoose.Schema({
    code: { type: String, search : true },
    description: { type: String }
});

nestedSchema.plugin(encrypt, { secret: secrets.encryption.secret, encryptedFields: ['code'], collectionId : 'nestedData' ,decryptPostSave: true});

var encryptSchema = new mongoose.Schema({
    first_name: { type: String },
    last_name: { type: String },
    mobilenumber: { type: String, search : true },
    nestedData: {type : nestedSchema} 
});

encryptSchema.plugin(encrypt, { secret: secrets.encryption.secret, encryptedFields: ['mobilenumber'] , decryptPostSave: true});

Encrypt = mongoose.model('Encrypt', encryptSchema);
module.exports = Encrypt;
`
After the record is saved i am getting code as undefined in the post save response. Here is a sample record that i tried to save with the response being returned after save.

`var encrypt = new EncryptModel({ first_name: 'John', last_name: 'Doe', mobilenumber: '1111111111',nestedData : {code :'abc' , 'description' : 'test'} });
`
Response 

`{ _id: 5af43d9108478e93001cf168,
  nestedData: 
   { _id: 5af43d9108478e93001cf169,
     description: 'test',
     code: undefined,
     _ct: 
      Binary {
        _bsontype: 'Binary',
        sub_type: 0,
        position: 33,
        buffer: <Buffer 61 4a f7 3f f5 7b 98 f2 f4 be a0 51 7a ad 3c b4 91 6e 14 62 c2 fe cb 61 c2 cd 99 c6 40 8f 82 fe b2> },
     _ac: 
      Binary {
        _bsontype: 'Binary',
        sub_type: 0,
        position: 46,
        buffer: <Buffer 61 d3 b6 3e 8b f5 ba 19 8e 51 94 cb 88 26 b3 20 cf 3b 8d ac ec 93 d9 19 98 06 a8 15 8d e3 75 f9 2f 5b 22 5f 69 64 22 2c 22 5f 63 74 22 5d> } },
  mobilenumber: '1111111111',
  last_name: 'Doe',
  first_name: 'John',
  _ct: undefined,
  _ac: undefined,
  __v: 0 }`

Can you please let me know if i am missing some configuration.?

Thanks,

**Comment by joegoldbeck** [comment]
Fixed as of [2.0.0](https://github.com/joegoldbeck/mongoose-encryption/tree/2.0.0)
