### ISSUE TITLE
encryptedFields with multiple fields

### ISSUE THREAD

**Issue by Themandunord** [joegoldbeck/mongoose-encryption#81]
Hello,

I try to encrypt two fields in my model.

Schema:
```
...
content: String,
providerReceivedContent: String,
...
```

And the configuration : 
```
 schema.plugin(encrypt, {
    requireAuthenticationCode: false,
    encryptionKey: encKey,
    signingKey: sigKey,
    encryptedFields: ['providerReceivedContent', 'content']
  });
```

Only content is encrypted.

If I put only `providerReceivedContent`, the field is encrypted.

I don't understand why, do you see a mistake? Do you need more information about the schema? 

Thank you

**Comment by joegoldbeck** [comment]
Hi @Themandunord this seems odd! I can't see any obvious mistake, but if you paste a larger code chunk I'm happy to take a look through.

What versions of Node, Mongoose, and this plugin are you using?

**Comment by Themandunord** [comment]
OK... I found the issue.
I use `findOneOrUpdate` on the filed `providerReceivedContent`. So Mongoose don't have the pre hook.
I replace it with a `findOne` and `save`

Thanks for you support ;)

**Comment by joegoldbeck** [comment]
Ah! That make sense. 

🦆 🛁
