### ISSUE TITLE
Snyk reported vulnerability in mpath 0.4.1

### ISSUE THREAD

**Issue by fracmak** [joegoldbeck/mongoose-encryption#84]
https://app.snyk.io/test/npm/mongoose-encryption/2.0.1

Appears mpath has a high severity flaw in it that was fixed in 0.5.1. We should upgrade to that version to clear up the error

**Comment by yelworc** [comment]
This has apparently [made its way to npm now](https://www.npmjs.com/advisories/779) (wonder why that took so long…), so npm is complaining about it.
I just tried updating the dependency, at first glance it doesn't seem to do any harm. Will submit a PR.

**Comment by joegoldbeck** [comment]
Fixed in 2.0.2 

Thanks for there PR :D
