### ISSUE TITLE
Error with @types installation

### ISSUE THREAD

**Issue by mukunddeepak** [joegoldbeck/mongoose-encryption#93]
Could not find a declaration file for module 'mongoose-encryption'. 'c:/Users/rema/Desktop/Secrets/node_modules/mongoose-encryption/index.js' implicitly has an 'any' type.
  Try `npm install @types/mongoose-encryption` if it exists or add a new declaration (.d.ts) file containing `declare module 'mongoose-encryption';`
error shown above .

**Comment by joegoldbeck** [comment]
hi @mukunddeepak apologies. there is no explicit `@types` support for the `mongoose-encryption` package. If this compatibility is indeed lacking and could be addressed easily, welcome any simple PRs that would add that support.

**Comment by joegoldbeck** [comment]
Hopefully this should be fixed as of `2.0.3`
